# Generated by Django 2.1.5 on 2019-01-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0002_auto_20190127_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500)),
                ('imagefile', models.ImageField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='images',
        ),
    ]
