# Generated by Django 2.1.5 on 2019-01-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0003_auto_20190131_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processingf',
            field=models.ImageField(null=True, upload_to='images/processed'),
        ),
    ]
