# Generated by Django 2.1.5 on 2019-02-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0004_image_processingf'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='area',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='depth',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='no_of_pothole',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
