# Generated by Django 2.1.5 on 2019-02-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0005_auto_20190208_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lat',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='long',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
